version: 1
runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

vm_health_check:
  enable_health_check: False

health_check:
  enable_health_check: False

handlers:

- url: /(.*\.(html|css|js))
  static_files: static/\1
  upload: static/(.*\.(html|css|js))

- url: /.*
  script: server.js
